### ISSUE TITLE
found a bug ?

### ISSUE THREAD

**Issue by ieeeee** [Normal-Tangerine8609/Scriptable-HTML-Widget#1]
Should line 178 of the file [/code/html-widget-expanded.js] be replaced with addons = {blockquote ,hr,symbol ,progress } to use the built-in plug-in?

**Comment by Normal-Tangerine8609** [comment]
Yes, that line of code was incorrect and is now fixed. While I was looking at it, I also noticed that the hr addon was not in the file meaning that you would not be able to use `<hr>`  even if you had added addons. Both things are now fixed, thanks for raising this bug.
